spring.application.name=product-service

spring.datasource.url=jdbc:postgresql://localhost:5432/bts-db-product
spring.datasource.username=postgres
spring.datasource.password=inipass
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

#SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.oauth2.resourceserver.jwt.secret=my-super-secret-key-for-product-service-app